### PR TITLE
Mabasa Nyasha Mutyambizi 202025800045-Fixed Bug 51: 

### PR DESCRIPTION
**Pull request by MabasaDailyCode**
Fixed Bug 51: Unable to find course after entering the course code.

### CODE REVIEW

**Comment by MabasaDailyCode** [comment]
Unable to find the course after entering the correct course number.
http://118.25.96.118/bugzilla/show_bug.cgi?id=51

**Comment by spm2020spring** [comment]
@Mabasa-elexma It seems that LRR is able to return something before your change.  Why is that?

image

**Comment by Mabasa-elexma** [comment]
> @Mabasa-elexma It seems that LRR is able to return something before your change. Why is that?
> 
> image

**Comment by MabasaDailyCode** [comment]
> @Mabasa-elexma It seems that LRR is able to return something before your change. Why is that?
> 
> image

Because many users encountered the same issue using their current course code for instance the course code for software Engineering for masters students is CSC1101 but when you search using that code, the result will not be found because same course is differentiated by the course year such as 2019, 2020. Below is such a case whereby I noticed the same issue.  

Screenshot (9)_LI

**Comment by spm2020spring** [comment]
> CSC1101

I got the following when I entered CSC1101 as a student (before adopting your change).

-Hui

image

**Comment by spm2020spring** [comment]
@Mabasa-elexma 

This Pull Request makes an enhancement: it allows a student to find courses after entering a part of the course code, in case he forgets the whole course code.

However, it does not fix Bug# 51 (http://118.25.96.118/bugzilla/show_bug.cgi?id=51).

-Hui

**Pull request merged**
